---
- name: My first play
  hosts: all
  tasks:
  - name: Ping my hosts
    ansible.builtin.ping:
  
  # - name: "install nginx"
  #   apt:
  #     name: ['nginx']
  #     state: latest
  # - name: ensure nginx is at the latest version
  #   apt: name=nginx state=latest
  #   become: yes

  # - name: apt-get update
  #   become: yes
  #   apt:
  #     name: python-apt
  #     state: latest
  #   vars:
  #     ansible_python_interpreter: /usr/bin/python3
  
  # - name: "apt-get update"
  #   apt:
  #     update_cache: yes

  # - name: Update apt cache and install Nginx
  #   apt:
  #     name: nginx
  #     state: latest
  #     update_cache: yes
  #   become: yes
  
  # - name: start nginx
  #   service:
  #       name: nginx
  #       state: started
  #   become: yes
  # - name: copy the nginx config file and restart nginx
  #   copy:
  #     src: /home/foo/static_site.cfg
  #     dest: /etc/nginx/sites-available/static_site.cfg
  #   become: yes
  # - name: create symlink
  #   file:
  #     src: /etc/nginx/sites-available/static_site.cfg
  #     dest: /etc/nginx/sites-enabled/default
  #     state: link
  #   become: yes
  # - name: copy the content of the web site
  #   copy:
  #     src: /home/foo/static-site-src/
  #     dest: /home/foo/static-site
  # - name: restart nginx
  #   service:
  #     name: nginx
  #     state: restarted
  #   become: yes